# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 18:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_model', models.CharField(max_length=250)),
                ('photography_genre', models.TextField()),
                ('address', models.TextField()),
                ('website', models.URLField()),
                ('contacts', models.ManyToManyField(related_name='_imagerprofile_contacts_+', to='imager_profile.ImagerProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
