# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='imagerprofile',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='contacts',
            field=models.ManyToManyField(default='', related_name='_imagerprofile_contacts_+', to='imager_profile.ImagerProfile'),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='photography_genre',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='website',
            field=models.URLField(default=''),
        ),
    ]
